language: node_js
node_js:
  - "8.11.2"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
- yarn lint
notifications:
  email: false
  slack:
    secure: 
    on_success: change
    on_pull_requests: false
    template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
